esphome:
  name: comfoair
  platform: ESP8266
  board: nodemcu

# Disable uart logging
logger:
  baud_rate: 0

sensor:
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO4
      mode:
        input: true
        pullup: true
    name: "Mode button"
    filters:
      - invert:
      - delayed_on: 10ms
    on_multi_click:
      - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
        then:
          lambda: "id(comfoair_climate).set_level(3);"
      - timing:
        - ON for 1s to 2s
        - OFF for at least 0.5s
        then:
          lambda: "id(comfoair_climate).set_level(1);"
      - timing:
        - ON for at most 1s
        - OFF for at least 0.5s
        then:
          lambda: "id(comfoair_climate).set_level(2);"

uart:
- id: uart_bus
  baud_rate: 9600
  tx_pin: TX
  rx_pin: RX 
- id: uart_proxy
  baud_rate: 9600
  tx_pin: GPIO5
  rx_pin: GPIO14

external_components:
  - source:
      type: git
      url: https://github.com/julianpas/esphome-comfoair
    components: ["comfoair"]

button:
  - platform: restart
    id: reset_button
    name: "Reset Comfoair"
  - platform: template
    id: filter_reset_button
    name: "Reset Filter"
    on_press: 
      then:
        lambda: "id(comfoair_climate).reset_filters();"

switch:
  - platform: gpio
    pin: GPIO12
    name: "LED Green Light"
    id: green_led_gpio
  - platform: gpio
    pin: GPIO13
    name: "LED Blue Light"
    id: blue_led_gpio
  - platform: gpio
    pin: GPIO15
    name: "LED Red Light"
    id: red_led_gpio

comfoair:
  id: comfoair_climate
  name: "ComfoAir 310 SL"
  uart_id: uart_bus
  proxy_uart: uart_proxy
  red_led: red_led_gpio
  green_led: green_led_gpio
  blue_led: blue_led_gpio
  type:
    name: "type"
  size:
    name: "size"
  intake_fan_speed:
    name: "intake_fan_speed"
  exhaust_fan_speed:
    name: "exhaust_fan_speed"
  intake_fan_speed_rpm:
    name: "intake_fan_speed_rpm"
  exhaust_fan_speed_rpm:
    name: "exhaust_fan_speed_rpm"
  ventilation_level:
    name: "ventilation_level"
  bypass_present:
    name: "bypass_present"
  bypass_valve:
    name: "bypass_valve"
  bypass_valve_open:
    name: "bypass_valve_open"
  preheating_state:
    name: "preheating_state"
  outside_air_temperature:
    name: "outside_air_temperature"
  supply_air_temperature:
    name: "supply_air_temperature"
  return_air_temperature:
    name: "return_air_temperature"
  exhaust_air_temperature:
    name: "exhaust_air_temperature"
  enthalpy_temperature:
    name: "enthalpy_temperature"
  ewt_temperature:
    name: "ewt_temperature"
  reheating_temperature:
    name: "reheating_temperature"
  kitchen_hood_temperature:
    name: "kitchen_hood_temperature"
  return_air_level:
    name: "return_air_level"
  supply_air_level:
    name: "supply_air_level"
  supply_fan_active:
    name: "supply_fan_active"
  filter_status:
    name: "filter_status"
  filter_full:
    name: "is_filter_full"
  enthalpy_present:
    name: "enthalpy_present"
  ewt_present:
    name: "ewt_present"
  options_present:
    name: "options_present"
  fireplace_present:
    name: "fireplace_present"
  kitchen_hood_present:
    name: "kitchen_hood_present"
  postheating_present:
    name: "postheating_present"
  postheating_pwm_mode_present:
    name: "postheating_pwm_mode_present"
  preheating_present:
    name: "preheating_present"
  bypass_factor:
    name: "bypass_factor"
  bypass_step:
    name: "bypass_step"
  bypass_correction:
    name: "bypass_correction"
  bypass_open_hours:
    name: "bypass_open_hours"
  preheating_hours:
    name: "preheating_hours"
  level0_hours:
    name: "level0_hours"
  level1_hours:
    name: "level1_hours"
  level2_hours:
    name: "level2_hours"
  level3_hours:
    name: "level3_hours"
  preheating_valve:
    name: "preheating_valve"
  frost_protection_active:
    name: "frost_protection_active"
  frost_protection_hours:
    name: "frost_protection_hours"
  frost_protection_minutes:
    name: "frost_protection_minutes"
  frost_protection_level:
    name: "frost_protection_level"
  filter_hours:
    name: "filter_hours"
  motor_current_bypass:
    name: "motor_current_bypass"
  motor_current_preheating:
    name: "motor_current_preheating"
  summer_mode:
    name: "summer_mode"
  p10_active:
    name: "p10_active"
  p11_active:
    name: "p11_active"
  p12_active:
    name: "p12_active"
  p13_active:
    name: "p13_active"
  p14_active:
    name: "p14_active"
  p15_active:
    name: "p15_active"
  p16_active:
    name: "p16_active"
  p17_active:
    name: "p17_active"
  p18_active:
    name: "p18_active"
  p19_active:
    name: "p19_active"
  p90_active:
    name: "p90_active"
  p91_active:
    name: "p91_active"
  p92_active:
    name: "p92_active"
  p93_active:
    name: "p93_active"
  p94_active:
    name: "p94_active"
  p95_active:
    name: "p95_active"
  p96_active:
    name: "p96_active"
  p97_active:
    name: "p97_active"
  bathroom_switch_on_delay_minutes:
    name: "bathroom_switch_on_delay_minutes"
  bathroom_switch_off_delay_minutes:
    name: "bathroom_switch_off_delay_minutes"
  l1_switch_off_delay_minutes:
    name: "l1_switch_off_delay_minutes"
  boost_ventilation_minutes:
    name: "boost_ventilation_minutes"
  filter_warning_weeks:
    name: "filter_warning_weeks"
  rf_high_time_short_minutes:
    name: "rf_high_time_short_minutes"
  rf_high_time_long_minutes:
    name: "rf_high_time_long_minutes"
  extractor_hood_switch_off_delay_minutes:
    name: "extractor_hood_switch_off_delay_minutes"

# Enable Home Assistant API
api:
  encryption:
    key: !secret comfoair_encryption_key

ota:
  password: !secret comfoair_ota_password
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Comfoair Fallback Hotspot"
    password: !secret comfoair_ap_password

captive_portal:
    